=== MeDeity/auto-dragalia/src/locales/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/NateScarlet/auto-dragalia/master/src/locale/schema.json",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "$id": {
      "type": "string"
    },
    "banner": {
      "type": "string"
    },
    "idle-text": {
      "type": "string"
    },
    "repeat-raid": {
      "type": "string"
    },
    "feed-dragon": {
      "type": "string"
    },
    "feed-four-leaf-clover": {
      "type": "string"
    },
    "farm-rare-item": {
      "type": "string"
    },
    "present-button-not-found": {
      "type": "string"
    },
    "no-present-available": {
      "type": "string"
    },
    "transform-to-dragon": {
      "type": "string"
    },
    "use-dragon-skill": {
      "type": "string"
    },
    "no-support-skill-available": {
      "type": "string"
    },
    "use-support-skill": {
      "type": "string"
    },
    "image-not-found": {
      "type": "string"
    },
    "image-found": {
      "type": "string"
    },
    "wait-timeout": {
      "type": "string"
    },
    "wait-image-appear": {
      "type": "string"
    },
    "wait-image-disappear": {
      "type": "string"
    },
    "run-task": {
      "type": "string"
    },
    "team-too-weak": {
      "type": "string"
    },
    "closeness-reach-lv29": {
      "type": "string"
    },
    "no-clover": {
      "type": "string"
    },
    "entering-stage-1": {
      "type": "string"
    },
    "entered-stage-1": {
      "type": "string"
    },
    "entering-stage-2": {
      "type": "string"
    },
    "require-level-select-page": {
      "type": "string"
    },
    "rare-item-dropped": {
      "type": "string"
    },
    "no-rare-item-drop": {
      "type": "string"
    }
  },
  "required": [
    "$schema",
    "$id",
    "banner",
    "idle-text",
    "repeat-raid",
    "feed-dragon",
    "feed-four-leaf-clover",
    "farm-rare-item",
    "present-button-not-found",
    "no-present-available",
    "transform-to-dragon",
    "use-dragon-skill",
    "no-support-skill-available",
    "use-support-skill",
    "image-not-found",
    "image-found",
    "wait-timeout",
    "wait-image-appear",
    "wait-image-disappear",
    "run-task",
    "team-too-weak",
    "closeness-reach-lv29",
    "no-clover",
    "entering-stage-1",
    "entered-stage-1",
    "entering-stage-2",
    "require-level-select-page",
    "rare-item-dropped",
    "no-rare-item-drop"
  ]
}

=== MeDeity/auto-dragalia/src/locale/zh.json
{
  "$schema": "./schema.json",
  "$id": "https://raw.githubusercontent.com/NateScarlet/auto-dragalia/master/src/locale/zh.json",
  "banner": "${name}: 版本=${version}, 资产=${asset}, 语言=${locale}",
  "idle-text": "停止",
  "repeat-raid": "重复战斗",
  "feed-dragon": "自动喂龙",
  "feed-four-leaf-clover": "喂四叶草",
  "farm-rare-item": "刷稀有",
  "present-button-not-found": "未找到礼物按钮, 请手动前往龙之庭院",
  "no-present-available": "无可用礼物",
  "transform-to-dragon": "龙化",
  "use-dragon-skill": "使用龙技能",
  "no-support-skill-available": "支援技能不可用",
  "use-support-skill": "使用支援技能: ${pos}",
  "image-not-found": "未找到图像: ${id}",
  "image-found": "找到图像: ${id}: ${pos}",
  "wait-timeout": "等待超时",
  "wait-image-appear": "等待图像出现: ${id}",
  "wait-image-disappear": "等待图像消失: ${id}",
  "run-task": "运行任务: ${task}",
  "team-too-weak": "队伍战力不足, 无法通关",
  "closeness-reach-lv29": "信赖度已达到29级，若继续，请手动喂食",
  "no-clover": "没有四叶草，请去炼草",
  "entering-stage-1": "检测到正在进入第一关卡",
  "entered-stage-1": "检测到已进入第一关卡",
  "entering-stage-2": "检测到正在进入第二关卡",
  "require-level-select-page": "请至关卡选择页面再开始",
  "rare-item-dropped": "成功刷到稀有物品, 继续完成战斗",
  "no-rare-item-drop": "没有刷到稀有物品, 直接下一轮"
}

=== MeDeity/auto-dragalia/src/locale/en.json
{
  "$schema": "./schema.json",
  "$id": "https://raw.githubusercontent.com/NateScarlet/auto-dragalia/master/src/locale/en.json",
  "banner": "${name}: version=${version}, asset=${asset}, locale=${locale}",
  "idle-text": "Stopped",
  "repeat-raid": "RepeatRaid",
  "feed-dragon": "AutoDragonFeeding",
  "feed-four-leaf-clover": "FeedClovers",
  "farm-rare-item": "FarmRareItem",
  "present-button-not-found": "present button not found, Please go to the Dragons Roost manually",
  "no-present-available": "No presents available",
  "transform-to-dragon": "Transform to dragon",
  "use-dragon-skill": "Use dragon skill",
  "no-support-skill-available": "No support skill available",
  "use-support-skill": "Use support skill: ${pos}",
  "image-not-found": "Image not found: ${id}",
  "image-found": "Image found: ${id}: ${pos}",
  "wait-timeout": "Waiting timeout",
  "wait-image-appear": "Waiting image appear: ${id}",
  "wait-image-disappear": "Waiting image disappear: ${id}",
  "run-task": "Run task: ${task}",
  "team-too-weak": "Team not strong enough to clear the stage",
  "closeness-reach-lv29": "Closeness has reached 29，please，continue feeding manually so you don't waste anything",
  "no-clover": "You don't have any clovers，Please farm some",
  "entering-stage-1": "Loading of Stage 1 detected",
  "entered-stage-1": "Detected that Stage 1 has started",
  "entering-stage-2": "Detected entering 2nd Stage",
  "require-level-select-page": "Please go to the quest selection page to start",
  "rare-item-dropped": "Successfully obtained rare item, Continuing to complete the quest",
  "no-rare-item-drop": "No rare items were dropped, Move to the next round"
}
